/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsPinIndexRouteImport } from './routes/events.$pin.index'
import { Route as EventsPinSlugRouteImport } from './routes/events.$pin.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPinIndexRoute = EventsPinIndexRouteImport.update({
  id: '/events/$pin/',
  path: '/events/$pin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPinSlugRoute = EventsPinSlugRouteImport.update({
  id: '/events/$pin/$slug',
  path: '/events/$pin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$pin/$slug': typeof EventsPinSlugRoute
  '/events/$pin/': typeof EventsPinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$pin/$slug': typeof EventsPinSlugRoute
  '/events/$pin': typeof EventsPinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$pin/$slug': typeof EventsPinSlugRoute
  '/events/$pin/': typeof EventsPinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events/$pin/$slug' | '/events/$pin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/$pin/$slug' | '/events/$pin'
  id: '__root__' | '/' | '/events/$pin/$slug' | '/events/$pin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsPinSlugRoute: typeof EventsPinSlugRoute
  EventsPinIndexRoute: typeof EventsPinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$pin/': {
      id: '/events/$pin/'
      path: '/events/$pin'
      fullPath: '/events/$pin/'
      preLoaderRoute: typeof EventsPinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$pin/$slug': {
      id: '/events/$pin/$slug'
      path: '/events/$pin/$slug'
      fullPath: '/events/$pin/$slug'
      preLoaderRoute: typeof EventsPinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsPinSlugRoute: EventsPinSlugRoute,
  EventsPinIndexRoute: EventsPinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
