/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsIdRouteImport } from './routes/admin/events/$id'
import { Route as EventsPinIndexRouteImport } from './routes/events/$pin/index'
import { Route as EventsPinSlugRouteImport } from './routes/events/$pin/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const EventsPinIndexRoute = EventsPinIndexRouteImport.update({
  id: '/events/$pin/',
  path: '/events/$pin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPinSlugRoute = EventsPinSlugRouteImport.update({
  id: '/events/$pin/$slug',
  path: '/events/$pin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/events/$pin/$slug': typeof EventsPinSlugRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$pin/': typeof EventsPinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AdminIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/events/$pin/$slug': typeof EventsPinSlugRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/events/$pin': typeof EventsPinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/events/$pin/$slug': typeof EventsPinSlugRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$pin/': typeof EventsPinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/admin/'
    | '/admin/events/$id'
    | '/events/$pin/$slug'
    | '/admin/events/'
    | '/events/$pin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/admin'
    | '/admin/events/$id'
    | '/events/$pin/$slug'
    | '/admin/events'
    | '/events/$pin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/admin/'
    | '/admin/events/$id'
    | '/events/$pin/$slug'
    | '/admin/events/'
    | '/events/$pin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  EventsPinSlugRoute: typeof EventsPinSlugRoute
  EventsPinIndexRoute: typeof EventsPinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/events/$pin/': {
      id: '/events/$pin/'
      path: '/events/$pin'
      fullPath: '/events/$pin/'
      preLoaderRoute: typeof EventsPinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$pin/$slug': {
      id: '/events/$pin/$slug'
      path: '/events/$pin/$slug'
      fullPath: '/events/$pin/$slug'
      preLoaderRoute: typeof EventsPinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsIdRoute: typeof AdminEventsIdRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsIdRoute: AdminEventsIdRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  EventsPinSlugRoute: EventsPinSlugRoute,
  EventsPinIndexRoute: EventsPinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
