/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsIdRouteImport } from './routes/admin/events/$id'
import { Route as EventsPinIndexRouteImport } from './routes/events/$pin/index'
import { Route as EventsPinSlugRouteImport } from './routes/events/$pin/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/admin/events/',
  path: '/admin/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/admin/events/$id',
  path: '/admin/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPinIndexRoute = EventsPinIndexRouteImport.update({
  id: '/events/$pin/',
  path: '/events/$pin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPinSlugRoute = EventsPinSlugRouteImport.update({
  id: '/events/$pin/$slug',
  path: '/events/$pin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/events/$pin/$slug': typeof EventsPinSlugRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$pin/': typeof EventsPinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/events/$pin/$slug': typeof EventsPinSlugRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/events/$pin': typeof EventsPinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/events/$pin/$slug': typeof EventsPinSlugRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$pin/': typeof EventsPinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/events/$id'
    | '/events/$pin/$slug'
    | '/admin/events/'
    | '/events/$pin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/events/$id'
    | '/events/$pin/$slug'
    | '/admin/events'
    | '/events/$pin'
  id:
    | '__root__'
    | '/'
    | '/admin/events/$id'
    | '/events/$pin/$slug'
    | '/admin/events/'
    | '/events/$pin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminEventsIdRoute: typeof AdminEventsIdRoute
  EventsPinSlugRoute: typeof EventsPinSlugRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  EventsPinIndexRoute: typeof EventsPinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/admin/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$pin/': {
      id: '/events/$pin/'
      path: '/events/$pin'
      fullPath: '/events/$pin/'
      preLoaderRoute: typeof EventsPinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$pin/$slug': {
      id: '/events/$pin/$slug'
      path: '/events/$pin/$slug'
      fullPath: '/events/$pin/$slug'
      preLoaderRoute: typeof EventsPinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminEventsIdRoute: AdminEventsIdRoute,
  EventsPinSlugRoute: EventsPinSlugRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  EventsPinIndexRoute: EventsPinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
