apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'app.linguacast.audio'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "app.linguacast.audio"
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
  }
  compileSdk safeExtGet("compileSdkVersion", 36)
  lint {
    abortOnError false
  }
}

dependencies {
  implementation "androidx.media:media:1.7.0"
}
